version: '3.8'

services:
  app:
    build:
      context: .
    container_name: app
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - app_static:/app/static/static/
    depends_on:
      - db
#      - redis
    env_file:
      - ./.env-docker
    command: [ '/app/docker/app.sh' ]
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: db
    env_file:
      - ./.env-docker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

#  redis:
#    image: redis:7
#    container_name: redis
#    depends_on:
#      - db
#    env_file:
#      - ./.env
#    ports:
#      - 6379:6379
#    networks:
#      - app-network

#  celery:
#    build:
#      context: .
#    container_name: celery
#    command: [ '/app/docker/celery.sh', 'celery' ]
#    depends_on:
#      - redis
#    env_file:
#      - ./.env
#    networks:
#      - app-network

volumes:
  postgres_data:
  app_static:

networks:
  app-network:
    driver: bridge