version: '3.8'

services:
  web:
    build:
      context: .
    container_name: web
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./app/static:/app/static
    depends_on:
      - db
    env_file:
      - ./.env-docker

  db:
    image: postgres:15
    container_name: db
    env_file:
      - ./.env-docker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: