version: '3.8'

services:
  app:
    build:
      context: .
    container_name: app
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - app_static:/app/static/static/
    depends_on:
      - db
    env_file:
      - ./.env-docker
    command: [ '/app/docker/app.sh' ]

  db:
    image: postgres:15
    container_name: db
    env_file:
      - ./.env-docker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  app_static: